### ISSUE TITLE
Analyse fonctionnelle

### ISSUE THREAD

**Issue by gael0806** [gael0806/Maison_connectee#3]
faire une arborescence contenant toutes les fonctionnalités jusqu'au plus bas niveau

**Comment by ngolivier** [comment]
j'ai fait le diagramme de cas d'utilisation , je t'avouerai que je ne sais pas comment m'y prendre pour l'analyse fonctionnelle.

**Comment by gael0806** [comment]
Slt,


C'est déjà bien.
A valider par tous avant ajout dans le la doc.

2017-06-24 16:56 GMT+02:00 ngolivier <notifications@github.com>:
